### ISSUE TITLE
Source codes should not be deleted on reboot

### ISSUE THREAD

**Issue by borellim** [marvel-nccr/quantum-mobile#118]
Most of the code roles use `/tmp` as temporary folder for:
* downloading the source
* compiling
* testing

`/tmp` is generally emptied on reboot, so all the above steps are re-run when re-provisioning a machine that has been rebooted. This slows down development of the machine.

Proposal:
* change the base folder for all roles from `/tmp` to `/var/tmp`, which [is not (supposed to be) deleted on reboot](https://unix.stackexchange.com/questions/30489/what-is-the-difference-between-tmp-and-var-tmp);
* add to all roles an optional cleanup step [like the QE role](https://github.com/marvel-nccr/ansible-role-quantum-espresso/blob/v1.1.4/tasks/main.yml#L106..L110)
* Get in the habit of running `ansible-playbook playbook.yml --extra-vars "clean=true"` before creating the image, as is already documented in README.md

**Comment by ltalirz** [comment]
Hi Marco,
this is done on purpose in order to keep image size down (we're talking about 1-2 GB extra here I would say, feel free to re-check). 
Not only can it be very tedious to clean up any object files created during make; even the source code itself can be of substantial size e.g. if it's a git repository.

**Comment by chrisjsewell** [comment]
Yes I'm closing this as I don't intend to make this change, and I don't see it as being a common use case; that you need to re-provision a rebooted machine
