### ISSUE TITLE
switch from torque to slurm scheduler

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#63]
this is from @giovannipizzi 

I realized that the Torque scheduler by Ubuntu is very old and probably 
not even supported anymore.

Probably at some point we should investigate switching to slurm for 
quantum mobile and related machines - it might take some time to figure 
it out, but anyway there are updated packages in ubuntu (slurm-wlm, 
v.15.08 in xenial 16.04 and 17.11 in the most recent ubuntu,  which is 
also the most recent slurm version available: https://slurm.schedmd.com/).

Moreover, there are some resources around with dockerfiles and similar, 
so we can take inspiration:

https://github.com/giovtorres/slurm-docker-cluster

Note: I just realized that new Ubuntu versions do not even have 
anymore a torque package (but there is a slurm-wlm-torque package that 
has torque-syntax wrappers for slurm)

**Comment by ltalirz** [comment]
Keeping track of progress towards ubuntu 18.04 [here](https://github.com/marvel-nccr/quantum-mobile/issues/72#issuecomment-424868272)
This is now one of only two remaining issues.

**Comment by giovannipizzi** [comment]
This is now fixed! :-) As you see [here on Travis](https://travis-ci.org/marvel-nccr/ansible-role-slurm/builds/440141053?utm_source=github_status&utm_medium=notification ) now I also test the actual submission and that the job actually runs.

It required to use the correct configuration for SLURM 15.08 (I think the previous implementation was already for more recent versions of SLURM), and a few minor details e.g. regarding munge and some missing default values for the variables. Note that now, to make it idempotent, I don't regenenate the munge key if it is already there - I think this is generated by `apt-get install munge`, so it should be ok, but to be careful if we create a docker image that all should reuse, because then all will have the same key.

Only thing to note, that I put in the README, and needs to be taken care by Quantum Mobile (but it was the same also for Torque, and I think the logic is in not in the Torque role but in Quantum Mobile or in the role for its customizations, so probably it will work out of the box): 


> It is important that the hostname is properly set in the machine (both with hostname <HOSTNAME> and in the /etc/hosts/ file, in the line with the IP address (e.g. in docker this line should read 172.17.0.2 <HOSTNAME>, where <HOSTNAME> should be replaced with the hostname, and should match the variable slurm_hostname (default value: qmobile).

You can check what I do to make this happen in the .travis.yml file of the role.

I leave this issue open until when you integrate the role into Quantum Mobile and verify that it works also in there, and I let you close this.

**Comment by ltalirz** [comment]
Testing has now been moved from the .travis.yml to ansible (using molecule).
All that's left to be done is to adapt the update of the /etc/hosts file to virtualbox (using `when cloud_platform == 'virtualbox'`).
I will take care of this.

**Comment by ltalirz** [comment]
Fixed in 7d817d8ea28f13840f06b5e722d3ccd032b6d1a1
