### ISSUE TITLE
remaining interdependencies between roles

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#66]
- [ ] `common_bashrc_string` : is this dependency really necessary? this would add a new variable to quite a few roles...

**Comment by ltalirz** [comment]
Note: Also, the current way of inserting things above a certain line actually causes multiple copies to appear, e.g.
```
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
source /usr/local/bin/virtualenvwrapper.sh
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
source /usr/local/bin/virtualenvwrapper.sh
ulimit -s unlimited
export PATH=${PATH}:/home/max/codes/q-e-qe-6.2.1-fda42b8045f604ef8cc8400dac1b2a06cb3f6e91/bin
export PATH=${PATH}:/home/max/codes/yambo-4.2.1/bin
export PATH=${PATH}:/home/max/codes/fleur/build
export PATH=${PATH}:/home/max/codes/siesta-4.0.1/Obj
export PATH=${PATH}:/home/max/codes/cp2k-5.1/exe
export CP2K_DATA_DIR=/home/max/codes/cp2k-5.1/data
export PATH=${PATH}:/home/max/codes/wannier90-2.1
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
source /usr/local/bin/virtualenvwrapper.sh
ulimit -s unlimited
export PATH=${PATH}:/home/max/codes/q-e-qe-6.2.1-fda42b8045f604ef8cc8400dac1b2a06cb3f6e91/bin
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
source /usr/local/bin/virtualenvwrapper.sh
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
source /usr/local/bin/virtualenvwrapper.sh
ulimit -s unlimited
export PATH=${PATH}:/home/max/codes/q-e-qe-6.2.1-fda42b8045f604ef8cc8400dac1b2a06cb3f6e91/bin
export PATH=${PATH}:/home/max/codes/yambo-4.2.1/bin
export PATH=${PATH}:/home/max/codes/fleur/build
export PATH=${PATH}:/home/max/codes/siesta-4.0.1/Obj
export PATH=${PATH}:/home/max/codes/wannier90-2.1
```

I believe way to do it is to [add all stuff that isn't bash-related to .profile](https://superuser.com/a/789465/345438).
I.e. all the important setup (environment, ulimit -s, ...) will be done once when the user logs in.
Afterwards, typing "bash" just executes a very lightweight .bashrc

I've done first tests and it seems to work as intended.
@giovannipizzi Let me know in case you have any comments

**Comment by giovannipizzi** [comment]
I think the problem occurs when you do `ssh hostname command`, which will not then set the path (couldn't check now, but I think this is the case). This is problematic e. g. for workhorse or similar, when aiida is on a different machine and needs to run on that computer.

Maybe a good solution to avoid duplicates is to write everything in a custom file (e.g. ~/.shellcustomizations) and source it once only in .bashrc (if it exists)?

**Comment by ltalirz** [comment]
> I think the problem occurs when you do `ssh hostname command`, which will not then set the path

Hm, you are right:
```
18:22 $ ssh aws-aiida "which pw.x"
18:22 $ ssh aws-aiida 'bash -l -c "which pw.x"'
/home/aiida/codes/q-e-qe-6.2.1-fda42b8045f604ef8cc8400dac1b2a06cb3f6e91/bin/pw.x
```
> This is problematic e. g. for workhorse or similar, when aiida is on a different machine and needs to run on that computer.

Shouldn't AiiDA be using the login shell to execute commands (via `bash -l -c`)?
I.e. suppose AiiDA executes stuff on a computer that follows the proper rules of separation between `.bashrc` and `.profile`, then it would fail...

> Maybe a good solution to avoid duplicates is to write everything in a custom file (e.g. ~/.shellcustomizations) and source it once only in .bashrc (if it exists)?

I also thought about this and it's certainly better than the old way of doing it.
What I don't like about it is that the file name will be non-standard ([here they suggest .environ for exactly this purpose](https://superuser.com/a/789499/345438)) and that whatever we put in there will be needlessly sourced every time you open a bash shell in the normal Quantum Mobile VM.

**Comment by ltalirz** [comment]
e.g. for testing: just stupidly replacing this line
https://github.com/aiidateam/aiida_core/blob/7086bb8215844b632fae274a81ff7d4b394f1c78/aiida/transport/plugins/ssh.py#L1327

by
```
        s = 'bash -l -c "'+ command_to_execute + '"'
        print(s)
        channel.exec_command(s)
```
causes `.profile` to be sourced during `verdi computer test` on the aws machine.

**Comment by giovannipizzi** [comment]
Yes, but I would avoid changing that line - already escaping is complicated, and adding other layer of double quotes risks to possibly create even worse problems. Another option is , a few lines above, beside changing directory, also sourcing `.profile` if it exists (or `.bash_profile`, but then the logic of which files to source and in which order becomes complex...).

I'm not worried about the roles assuming the existence of the file (if you use lineinfile it should be ok), but I understand your concern about checking for the line sourcing it in `.bashrc` in every role, and I don't think I have a good solution for it yet.

As a note, I checked the source code of `lineinfile`: https://github.com/ansible/ansible/blob/c3a805aa3c919f5be82e8211544f83de5cd3aead/lib/ansible/modules/files/lineinfile.py#L338 
and it looks to me that the issue is that if there is no regexp defined and there is insertbefore, it adds the line *immediately before* the one specified, resulting in the fact (I couldn't test but I believe it is the case) that if we do the insertbefore twice, and run many times ansible, it will add many times the pair of lines.

**Comment by ltalirz** [comment]
PR https://github.com/aiidateam/aiida_core/pull/1502 lets AiiDA use login shells, i.e. from `v0.12.1` onwards, using `.profile` should be fine.
I.e. we will stick with adding environment variables to `.profile`.
