### ISSUE TITLE
dead link in this repository description

### ISSUE THREAD

**Issue by adegomme** [marvel-nccr/quantum-mobile#92]
https://materialscloud.org/quantum-mobile leads to a blank page. 
https://materialscloud.org/work/quantum-mobile seems to be working.

**Comment by ltalirz** [comment]
thanks!
fixed

**Comment by ltalirz** [comment]
by the way, aiida 0.12.3 is also on its way and I'm hopeful we'll see a quantum mobile release 19.02 in a couple of days

**Comment by adegomme** [comment]
I'm currently adding bigdft (and v_sim) to the set of codes. This should be ready very soon as well (tomorrow I think, I have to test it and determine where to push everything).

**Comment by ltalirz** [comment]
Cool! Are you preparing ansible role for these?

If yes:
 * the [cookiecutter recipe](https://github.com/marvel-nccr/cookiecutter-ansible-role) that I use may be helpful
 * it might be nice to host your role repositories under the marvel-nccr github organization so that others can find it more easily (of course with you remaining the administrator). If you're interested, just let me know

**Comment by adegomme** [comment]
Yes ansible roles are mostly done, I just need to add the tests and validate everything (I can't do it now I have a terrible connection this afternoon). I didn't use cookiecutter, but copied a preexisting role (siesta) after building everything once.
Hosting everything under marvel-nccr org is probably the best solution, we will come back to you asap when everything is ready.
